/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelAndView struct {
	Empty bool `json:"empty,omitempty"`
	Model interface{} `json:"model,omitempty"`
	ModelMap map[string]interface{} `json:"modelMap,omitempty"`
	Reference bool `json:"reference,omitempty"`
	Status string `json:"status,omitempty"`
	View *View `json:"view,omitempty"`
	ViewName string `json:"viewName,omitempty"`
}
