/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserDto struct {
	FullName string `json:"fullName,omitempty"`
	Id int64 `json:"id,omitempty"`
	Password string `json:"password,omitempty"`
	RoleDto *RoleDto `json:"roleDto,omitempty"`
	Username string `json:"username,omitempty"`
}
