/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ServiceInfoDto struct {
	HairdresserDto *HairdresserDto `json:"hairdresserDto,omitempty"`
	Id int64 `json:"id,omitempty"`
	Price int64 `json:"price,omitempty"`
	ServiceDto *ServiceDto `json:"serviceDto,omitempty"`
}
