/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HairdresserDto struct {
	Description string `json:"description,omitempty"`
	FullName string `json:"fullName,omitempty"`
	Id int64 `json:"id,omitempty"`
	Phone string `json:"phone,omitempty"`
}
